/** @format */

import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";

const league_spartan = League_Spartan({
    subsets: ["latin"],
    weight: ["500", "700"],
});

export const metadata: Metadata = {
    title: "job list filter",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={league_spartan.className}>{children}</body>
        </html>
    );
}
